### register
curl --location --request POST 'https://127.0.0.1:3000/v1/register' \
--header 'Content-Type: application/json' \
--data '{
    "username": "stevenhdzx10",
    "password": "Admin*ñ1"
}'

### auth
curl --location --request POST 'https://127.0.0.1:3000/v1/login' \
--header 'Content-Type: application/json' \
--data '{
    "username": "stevenhdzx10",
    "password": "Admin*ñ1"
}'

### user info
curl --location --request POST 'https://127.0.0.1:3000/v1/information/external/one' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTc5NTI3NiwianRpIjoiNDcyOTMzMDYtZWFmZS00N2QwLWE2ZDItMzliMjE3MTllYzFlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkengxMCIsIm5iZiI6MTcxNTc5NTI3NiwiY3NyZiI6IjllYmNhZmM3LWFmNTctNDBjNS05ZGJlLTdmZjljOGZlODViNSIsImV4cCI6MTcxNTc5NTc3Nn0.67ZTUuLx_d5odWjsoQ2RuS-jD9FaH0HJ-8zcRUNoVf3kF4A-oMUS_87hjnknxngio3BJ6FR1ADcwyYJKVBHQjw' \
--data '{
    "id": 2
}'

### users info
curl --location --request POST 'https://127.0.0.1:3000/v1/information/external' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTc5MjQ5NCwianRpIjoiMDQ0MmQwZTEtNDgxYy00OTMxLTljZWEtYTMwMzBhMTg2ODBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkeng0IiwibmJmIjoxNzE1NzkyNDk0LCJjc3JmIjoiMDBlYTkzMzUtOTBkYi00MDZiLTkwYTktYjE4OTkzMTc2Njk4IiwiZXhwIjoxNzE1NzkyOTk0fQ.InGl6v-I7nUmrlB1TU0ekY9bCMnHMFDi1IIHvsD0TgH0MKiIPUFhGWvN3oeleuRtiqOKilFoAfK0y6VMCJMYQQ'

### logout
curl --location --request POST 'https://127.0.0.1:3000/v1/logout' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTc5MjQ5NCwianRpIjoiMDQ0MmQwZTEtNDgxYy00OTMxLTljZWEtYTMwMzBhMTg2ODBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkeng0IiwibmJmIjoxNzE1NzkyNDk0LCJjc3JmIjoiMDBlYTkzMzUtOTBkYi00MDZiLTkwYTktYjE4OTkzMTc2Njk4IiwiZXhwIjoxNzE1NzkyOTk0fQ.InGl6v-I7nUmrlB1TU0ekY9bCMnHMFDi1IIHvsD0TgH0MKiIPUFhGWvN3oeleuRtiqOKilFoAfK0y6VMCJMYQQ'

### route no exists any
curl --location --request POST 'https://127.0.0.1:3000/v1/PRUEBA'

### route DOCS swagger
curl --location --request GET 'https://127.0.0.1:3000/v1/swagger'