### register [queda con el role user]
curl --location --request POST 'https://127.0.0.1:3000/v1/register' \
--header 'Content-Type: application/json' \
--data '{
    "username": "stevenhdzx18",
    "password": "Admin*ñ1"
}'

### auth [username admin - password admin, username rrhh, password rrhh]
curl --location --request POST 'https://127.0.0.1:3000/v1/login' \
--header 'Content-Type: application/json' \
--data '{
    "username": "stevenhdzx18",
    "password": "Admin*ñ1"
}'

### user info
curl --location --request POST 'https://127.0.0.1:3000/v1/information/external/one' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTg4NTE5MiwianRpIjoiZjMyNjE3NjMtZTgxYS00ZDRlLTkwNzUtMDRkZjkxYTU0ZjVkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkengxOCIsIm5iZiI6MTcxNTg4NTE5MiwiY3NyZiI6ImQ0NDY2OTU4LWE4YTctNGExZS05MTZkLTcwODE0NjYyNzE4MCIsImV4cCI6MTcxNTg4NTY5Mn0.grDrfsE_ga2m6J8-6-tk3l52B3zTz8EyTzjgk6CXV41Lz4PyMfAQGIJEA3kvMstZqBzxaRhD3MZSE5dr1PzA_Q' \
--data '{
    "id": 2
}'

### users info
curl --location --request POST 'https://127.0.0.1:3000/v1/information/external' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTgxMjU1NCwianRpIjoiNTk0NTYyNTctMjA5ZC00YzQ4LWIyNDktYzlhNmE5N2NiMzNkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkengxOCIsIm5iZiI6MTcxNTgxMjU1NCwiY3NyZiI6ImNlMjU3OTdlLTFjZmUtNDhhMS04Yjk3LTc3MGU0YjBkNmI4MiIsImV4cCI6MTcxNTgxMzA1NH0.5cRwkw1gKXDQkVqZ1rLLFGBaNMOP4BTTHPUnMyIikFvccN_zuztD6jcASZWzGMaWVlbFaCKUZbTAjToc8gZzjg'

### logout
curl --location --request POST 'https://127.0.0.1:3000/v1/logout' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNTc5MjQ5NCwianRpIjoiMDQ0MmQwZTEtNDgxYy00OTMxLTljZWEtYTMwMzBhMTg2ODBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN0ZXZlbmhkeng0IiwibmJmIjoxNzE1NzkyNDk0LCJjc3JmIjoiMDBlYTkzMzUtOTBkYi00MDZiLTkwYTktYjE4OTkzMTc2Njk4IiwiZXhwIjoxNzE1NzkyOTk0fQ.InGl6v-I7nUmrlB1TU0ekY9bCMnHMFDi1IIHvsD0TgH0MKiIPUFhGWvN3oeleuRtiqOKilFoAfK0y6VMCJMYQQ'

### route no exists any
curl --location --request POST 'https://127.0.0.1:3000/v1/PRUEBA'

### route DOCS swagger
curl --location --request GET 'https://127.0.0.1:3000/v1/swagger'