version: "3"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  api:
    build:
      context: /
      dockerfile: Dockerfile
    restart: always
    links:
      - database
    ports:
      - "3000:3000"
    depends_on:
      - database
